#!/usr/bin/env bash
# Generates frigate/config.yml and docker-compose.yml from detected hardware.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

source "$SCRIPT_DIR/detect_hardware.sh"

# ── frigate/config.yml ────────────────────────────────────────────────────────
cat > "$PROJECT_DIR/frigate/config.yml" << FRIGATE_EOF
# Auto-generated by homewatch/scripts/generate_config.sh
# Hardware: $CPU_MODEL | RAM: ${RAM_GB}GB | Detector: $FRIGATE_DETECTOR_LABEL

mqtt:
  host: mosquitto
  port: 1883
  user: frigate
  password: frigate_pass

database:
  path: /data/frigate.db

# ── Detector ─────────────────────────────────────────────────────────────────
detectors:
FRIGATE_EOF

case "$FRIGATE_DETECTOR" in
coral)
cat >> "$PROJECT_DIR/frigate/config.yml" << 'EOF'
  coral:
    type: edgetpu
    device: usb
EOF
;;
onnx_cuda)
cat >> "$PROJECT_DIR/frigate/config.yml" << 'EOF'
  onnx:
    type: onnx
    device: cuda
EOF
;;
openvino)
cat >> "$PROJECT_DIR/frigate/config.yml" << 'EOF'
  ov:
    type: openvino
    device: AUTO
    model:
      path: /openvino-model/FP16/ssdlite_mobilenet_v2.xml
EOF
;;
*)
# CPU — one detector per allocated process
for i in $(seq 1 "$DETECT_PROCESSES"); do
cat >> "$PROJECT_DIR/frigate/config.yml" << EOF
  detector_cpu${i}:
    type: cpu
    num_threads: 2
EOF
done
;;
esac

cat >> "$PROJECT_DIR/frigate/config.yml" << FRIGATE_EOF

# ── FFMPEG ───────────────────────────────────────────────────────────────────
ffmpeg:
  hwaccel_args: $FFMPEG_PRESET
  output_args:
    record: preset-record-generic-audio-copy

# ── Snapshots globales ────────────────────────────────────────────────────────
snapshots:
  enabled: true
  timestamp: true
  bounding_box: true
  retain:
    default: $SNAPSHOTS_RETAIN_DAYS

# ── Grabación ─────────────────────────────────────────────────────────────────
record:
  enabled: true
  retain:
    days: $RETAIN_DAYS
    mode: motion           # graba solo cuando hay movimiento (ahorra espacio)
  events:
    retain:
      default: $RETAIN_DAYS
      mode: active_objects # retiene más tiempo si hay objeto detectado

# ── Detección de objetos ──────────────────────────────────────────────────────
objects:
  track:
    - person
    - car
    - truck
    - motorcycle
    - bicycle
    - dog
    - cat
  filters:
    person:
      min_area: 2000       # ignora detecciones muy pequeñas (ruido)
      min_score: 0.6
      threshold: 0.7
    car:
      min_area: 5000
      min_score: 0.6

# ── Cámaras ───────────────────────────────────────────────────────────────────
# Frigate requiere al menos una cámara. Esta es una cámara de ejemplo
# deshabilitada. Reemplaza los valores con los de tu cámara real,
# o ejecuta: bash scripts/scan_cameras.py  para detectarlas automáticamente.
cameras:
  mi_camara:
    enabled: false          # cambia a true cuando tengas los datos correctos
    ffmpeg:
      inputs:
        - path: rtsp://usuario:password@192.168.1.100:554/stream1
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    # zones:
    #   zona_entrada:
    #     coordinates: 0,720,1280,720,1280,0,0,0
    #     objects:
    #       - person

# ── Interfaz web ──────────────────────────────────────────────────────────────
ui:
  live_mode: mse
  timezone: America/Santiago

FRIGATE_EOF

echo "✓ frigate/config.yml generado"

# ── docker-compose.yml ────────────────────────────────────────────────────────
COMPOSE_FILE="$PROJECT_DIR/docker-compose.yml"

# NVIDIA runtime flag
NVIDIA_RUNTIME=""
NVIDIA_DEPLOY=""
if [[ "$GPU_TYPE" == "nvidia" ]]; then
    NVIDIA_RUNTIME="    runtime: nvidia"
    NVIDIA_DEPLOY="    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]"
fi

cat > "$COMPOSE_FILE" << COMPOSE_EOF
# Auto-generated by homewatch/scripts/generate_config.sh
# Hardware: $CPU_MODEL | RAM: ${RAM_GB}GB | Storage: ${STORAGE_TYPE^^}
name: homewatch

services:

  # ── MQTT Broker ─────────────────────────────────────────────────────────────
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
    networks:
      - homewatch

  # ── Frigate NVR ─────────────────────────────────────────────────────────────
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable${FRIGATE_IMAGE_SUFFIX:-}
    container_name: frigate
    restart: unless-stopped
    privileged: true          # needed for hardware access
$NVIDIA_RUNTIME
$NVIDIA_DEPLOY
    shm_size: "256mb"         # shared memory for frame buffers
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./frigate/config.yml:/config/config.yml
      - frigate_data:/data
      - frigate_media:/media/frigate
    ports:
      - "5000:5000"           # Frigate web UI
      - "8554:8554"           # RTSP re-streams
      - "8555:8555/tcp"       # WebRTC
      - "8555:8555/udp"
    environment:
      FRIGATE_RTSP_PASSWORD: "changeme"
    mem_limit: $FRIGATE_MEM_LIMIT
    depends_on:
      - mosquitto
    networks:
      - homewatch

  # ── Home Assistant ───────────────────────────────────────────────────────────
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./homeassistant/config:/config
    ports:
      - "8123:8123"           # Home Assistant web UI
    environment:
      TZ: America/Santiago
    depends_on:
      - mosquitto
      - frigate
    networks:
      - homewatch

volumes:
  mosquitto_data:
  mosquitto_log:
  frigate_data:
  frigate_media:

networks:
  homewatch:
    driver: bridge

COMPOSE_EOF

echo "✓ docker-compose.yml generado"
